server:
  port: 8081

#  对象的两种写法
#firends:{lastName: 'zhangsan' ,age: 20 }

#firends2:
#     lastName: zhangsan
#     age: 20

#数组的两种写法
#pets: [cat,daog,pig]
# -空格 值  表示数组中的一个元素
#pets2:
#  - cat
#  - dog
#  - pig

#   <!--导入配置文件处理器，配置文件进行绑定就会有提示 例：person下输入a则age就提示出来了-->
#        <dependency>
#            <groupId>org.springframework.boot</groupId>
#            <artifactId>spring-boot-configuration-processor</artifactId>
#            <optional>true</optional>
#        </dependency>

#person:
#    lastName: 张4
#    age: 18
#    maps: {aaa: aaa,bbb: bbb,ccc: ccc}
#    lists:
#       - a
#       - b
#       - c